# Generated by Django 5.1.7 on 2025-03-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_x', models.PositiveIntegerField()),
                ('max_y', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('orientation', models.CharField(choices=[('N', 'N'), ('S', 'S'), ('E', 'E'), ('O', 'O')], max_length=1)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='drones.matrix')),
            ],
        ),
    ]
